<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="List" nsURI="List" nsPrefix="List">
  <eClassifiers xsi:type="ecore:EClass" name="List">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstElement" eType="#//Element"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastElement" eType="#//Element"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testPointer" eType="#//List"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packagePointer" eType="#//TestPackage/Test"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//listType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="listType">
    <eLiterals name="ArrayList"/>
    <eLiterals name="List" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subElements" eType="#//List"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTestPointer" eType="#//TestPackage/SubTestPackage/SubTest"
        eOpposite="#//TestPackage/SubTestPackage/SubTest/elementPointer"/>
  </eClassifiers>
  <eSubpackages name="TestPackage" nsURI="TestPackage" nsPrefix="TestPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Test">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementPointer" eType="#//Element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementPointer2" eType="#//Element"/>
    </eClassifiers>
    <eSubpackages name="SubTestPackage" nsURI="SubTestPackage" nsPrefix="SubTestPackage">
      <eClassifiers xsi:type="ecore:EClass" name="SubTest">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="elementPointer" eType="#//Element"
            eOpposite="#//Element/subTestPointer"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
