<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="my" nsURI="my" nsPrefix="my">
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1" eType="//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ListFeatures" upperBound="-1" eType="//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ElementFeature" eType="//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueElement" eSuperTypes="//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLists" upperBound="-1" eType="//List" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFeatures" upperBound="-1" eType="//Feature" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
