/**
 *
 * $Id$
 */
package my.validation;

import my.Element;
import my.Feature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link my.List}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ListValidator {
	boolean validate();

	boolean validateOwnedElements(EList<Element> value);
	boolean validateListFeatures(EList<Feature> value);
	boolean validateSize(int value);
}
